---
title: "Bayesian software"
output: html_document
date: "2023-05-01"
---

Based on slides: https://drive.google.com/drive/folders/1Gw4xOqK1vijalFvP-WWJP030NIyt3nKz
But data are simulaetd
Step 1: install and load the packages
```{r}
#install.packages("R2OpenBUGS")
#install.packages("coda")
#install.packages("readr")
#install.packages("nimble")
#install.packages("HDInterval")


library("R2OpenBUGS")
library("coda")
library("readr")
library("nimble")
library("HDInterval")
```



```{r q2_theta_plus}
alpha_plus <- 172
beta_plus <- 3265
confidence_level <- 0.95

# Median
median_plus <- qbeta(0.5, alpha_plus, beta_plus)

## EQUAL TAIL CI
equal_tail_plus <- c(qbeta(0.025,alpha_plus,beta_plus),qbeta(0.975,alpha_plus,beta_plus))

## HPD CI
hpdbeta <- function(alpha,beta)
{
p2 <- alpha
q2 <- beta

f <- function(x,p=p2,q=q2){
b<-qbeta(pbeta(x,p,q)+0.95,p,q);(dbeta(x,p,q)-dbeta(b,p,q))^2}

hpdmin <- optimize(f,lower=0,upper=qbeta(0.05,p2,q2),p=p2,q=q2)$minimum
hpdmax <- qbeta(pbeta(hpdmin,p2,q2)+0.95,p2,q2)
return(c(hpdmin,hpdmax))
}
hpd_interval_plus<-hpdbeta(alpha_plus,beta_plus)
```

```{r q2_theta_minus}
alpha_minus <- 118
beta_minus <- 4321
confidence_level <- 0.95

# Median 
median_minus <- qbeta(0.5, alpha_minus, beta_minus)

## EQUAL TAIL CI
equal_tail_minus <- c(qbeta(0.025,alpha_minus, beta_minus),qbeta(0.975,alpha_minus, beta_minus))

## HPD CI
hpd_interval_minus<-hpdbeta(alpha_minus, beta_minus)

```


```{r generate_samples_q3}
num_samples <- 5000
theta_plus_samples <- numeric(num_samples)
theta_minus_samples <- numeric(num_samples)
relative_risk_samples <- numeric(num_samples)

alpha_plus <- 172
beta_plus <- 3265
alpha_minus <- 118
beta_minus <- 4321

for (i in 1:num_samples) {
  theta_plus <- rbeta(1, alpha_plus, beta_plus)
  theta_minus <- rbeta(1, alpha_minus, beta_minus)
  
  theta_plus_samples[i] <- theta_plus
  theta_minus_samples[i] <- theta_minus
  relative_risk_samples[i] <- theta_plus / theta_minus
}

par(mfrow = c(1, 3))
hist(theta_plus_samples, breaks = 30, col = "lightblue", xlab = "", main = "")
hist(theta_minus_samples, breaks = 30, col = "lightblue", xlab = "", main = "")
hist(relative_risk_samples, breaks = 30, col = "lightblue", xlab = "", main = "")
```


```{r get_summary_q3}
mean_rr <- mean(relative_risk_samples)
mode_rr <- get_mode(relative_risk_samples)
var_rr <- var(relative_risk_samples)
confidence_interval_rr <-quantile(relative_risk_samples, probs = c(0.025,0.50,0.975), na.rm = F)
hdi_rr<-hdi(relative_risk_samples)

mean_tp <- mean(theta_plus_samples)
mode_tp <- get_mode(theta_plus_samples)
var_tp <- var(theta_plus_samples)
confidence_interval_tp <-quantile(theta_plus_samples, probs = c(0.025,0.50,0.975), na.rm = F)
hdi_tp<-hdi(theta_plus_samples)

mean_tm <- mean(theta_minus_samples)
mode_tm <- get_mode(theta_minus_samples)
var_tm <- var(theta_minus_samples)
confidence_interval_tm <-quantile(theta_minus_samples, probs = c(0.025,0.50,0.975), na.rm = F)
hdi_tm<-hdi(theta_minus_samples)

```

